### ISSUE TITLE
No object fits the selected criteria. Please change the filter settings.

### ISSUE THREAD

**Issue by pixelhaufen** [Wikimedia-Austria/WikiDaheim#101]
The backend can't deal with the random/fantasy Gemeindekennzahl if somebody clicks on the map.

- Klosterneuburg 32408
- Mauerbach 32412
- Gablitz 32403
- Tullnerbach 32421
- Purkersdorf 32416
- Pressbaum 32415
- Wolfsgraben 32423
- Straß in Steiermark 61058
- Murfeld 62347
- Sankt Veit in der Südsteiermark 61056
- ...

It would be possible to map those to the correct ones, however somebody would have to create a list of all fantasy numbers and the correct ones.

However there is no way to fix 'Breitenfurt bei Wien' (Q662190 vs. Q693181) since it's the correct one of 'Laab im Walde'

**Comment by reiterbene** [comment]
Is this a complete list or are there a lot more wrong GKZs? As the mapping file from Mapbox-IDs to GKZs is locally included in the Web-App I can fix the incorrect numbers directly on the client side.

**Comment by pixelhaufen** [comment]
No, that's just what I found clicking around on the map... I can offer you a list of all GKZs from wp. [Gemeinde_Wikidata_Kennzahl.csv.zip](https://github.com/Wikimedia-Austria/WikiDaheim/files/4996459/Gemeinde_Wikidata_Kennzahl.csv.zip) Can you compare this with the list in the app to find different entries?

**Comment by reiterbene** [comment]
@BraveheartWikimedia
The mapping can be found in this file: https://github.com/Wikimedia-Austria/WikiDaheim/blob/master/src/config/boundaries.json
If requested I can have a look into this.

**Comment by pixelhaufen** [comment]
Here is a diff for the data:

Gemeinde | GKZ  | GKZ
-- | -- | --
Sankt Veit in der  Südsteiermark | 61060 | 61056
Straß in Steiermark | 61061 | 61058
Peuerbach | 40835 | 40819
Helfenberg | 41345 | 41310
St. Stefan-Afiesl | 41346 |  -
Schwanberg (Steiermark) | 60349 |  -


GKZ | Gemeinde
-- | --
40803 | Bruck-Waasen
41340 | Schönegg

**Comment by BraveheartWikimedia** [comment]
@reiterbene Yes please - I assume the boundaries file needs to be changed to reflect the actual municipality keys?

**Comment by reiterbene** [comment]
@BraveheartWikimedia in the current branch I have integrated an interactive mapping editor. Just checkout the branch and run "yarn check:boundaries" in the terminal. After running through the wizard a new mapping file will be generated which you can push into the branch.

**Comment by BraveheartWikimedia** [comment]
@reiterbene Thanks (and sorry for the late reply)! Is this boundary-check still necessary or did you fix that back in September?

BR, Philip

**Comment by reiterbene** [comment]
Hey@BraveheartWikimedia,

yes, I am still waiting for you to run the boundary checker.

**Comment by BraveheartWikimedia** [comment]
Ok, will do this tonight!

**Comment by BraveheartWikimedia** [comment]
@reiterbene I've updated the boundary file and uploaded it as boundaries_mapped.json to the branch. Two municipalities don't have an ID anymore because they don't exist anymore (Bruck-Waasen and Schönegg), the rest should be ok. Not sure why Vienna needed to be remapped, hope I didn't mess something up.
