### ISSUE TITLE
Bilderwünsche do not disappear in WikiDaheim when deleted in WP

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#130]
see https://de.wikipedia.org/w/index.php?title=Diskussion:Liste_der_Kunstwerke_im_%C3%B6ffentlichen_Raum_in_Wien/Meidling&diff=prev&oldid=227435448&diffmode=source
(Mosaike auf der Seite Bonygasse 13, 4 Stück, 4 Jahreszeiten)
I removed the Bilderwunsch in Oktober 2022, but the Bilderwunsch is still shown in WikiDaheim. (navigate to Meidling)

When a Bilderwunsch is removed in WP, this should be synced with WikiDaheim and the Bilderwunsch shall also disappear in WikiDaheim.

**Comment by reiterbene** [comment]
This should also be an backend issue @pixelhaufen.

**Comment by HerziPinki** [comment]
after a change by @pixelhaufen, the Bilderwunsch in Bonygasse is gone.
