### ISSUE TITLE
wrong link for Impressum and Datenschutz

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#136]
https://wikimedia.at/ueber-uns/kontakt/impressum/  -> Oops! That page can’t be found.

a correct link is https://wikimedia.at/impressum-datenschutz/ (waiting for redirect)

**Comment by HerziPinki** [comment]
all occurences changed

**Comment by HerziPinki** [comment]
@benereiter 


> @HerziPinki did you change this in code as there is no commit present

I changed it in branch [texts-for-2023] (https://github.com/Wikimedia-Austria/WikiDaheim/tree/texts-for-2023), will commit when all text changes are done. (see https://github.com/Wikimedia-Austria/WikiDaheim/actions).
Did I do something wrong / unexpected?

**Comment by reiterbene** [comment]
no, sorry - just did not see the branch!
