### ISSUE TITLE
Server fails to send a reply for some municipalities

### ISSUE THREAD

**Issue by reiterbene** [Wikimedia-Austria/WikiDaheim#145]
> another case: https://wikidaheim.at/Q683136 (Gutau, OÖ)
> as far as I see, there was no change in municipality structure, but the behaviour is similar to Ahorn. 
> So this might be a separate issue. Please check.

_Originally posted by @HerziPinki in https://github.com/Wikimedia-Austria/WikiDaheim/issues/131#issuecomment-1564056852_

@pixelhaufen Gutau sends an empty response
https://api.wikidaheim.at/api.php?format=json&action=query&type=data&wikidata=Q683136&categories=request|denkmalliste|naturdenkmal|publicart|kellergasse|commons&wiki=1)

**Comment by reiterbene** [comment]
Frontend: add check for empty responses

**Comment by HerziPinki** [comment]
not a stable behaviour. not fixed, can't repro (pixelhaufen)

**Comment by reiterbene** [comment]
should be fixed together with #172
