### ISSUE TITLE
Update / complete technical doc

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#146]
can you please give me the links to the technical doc.

please do not forget to update technical doc. If something is missing, please complete technical doc.

**Comment by pixelhaufen** [comment]
back-end: https://cloud.demus.ch/index.php/s/Ap3zknaCKFeyTWT

**Comment by HerziPinki** [comment]
The purpose of this issue is to mitigate the risk, that one of you is not available any more. We don't need documentation now before starting WikiDaheim in 2023. It can be done till the end of 2023. Please include an effort estimation in your proposal into a separate point so that Claudia can decide. The goal of this documentation is that some tech people can maintain and run your code.

- the source of the front end is in GitHub. Right?
- where is the source of the back end, how to access?
- are there any configuration issues? I remember that adding new data sources to the back end is just configuration. How to access / change the configuration?
- where is the back end database? How to access? How to reset? How to start an update manually? etc.
- if the back end code is on pixelhaufens private cloud, ...

-----
- describe the underlying common architecture in a short document including the interfaces between the front and the back end. This part should be understandable also for tech people who do not dig into the code.
- an overview image would be fine
for both front and back end
- a (more detailed) overview image would be fine 
- describe the components with their dependencies and implementation choices and implementation (file) structure.
- mention the frameworks / libs etc. used and for what purpose
- administration (access data, permissions, web provider, etc.; ) - extra part for security
- maintainance (updating the map of Austria, new data sources, ...)
- deployment
- operation / surveillance / sanity checks
- performance related considerations
- anything else of importance

(if there already is something written, please tell me.)
