### ISSUE TITLE
Comma and period look similar when small

### ISSUE THREAD

**Issue by pkopetzky** [Wikimedia-Austria/WikiDaheim#17]
Comma and period look similar when either using a small resolution or a small font size (see screenshot attached). Is there any way to rectify this problem?
![comma and point screenshot](https://user-images.githubusercontent.com/12571157/29148691-29c18c8a-7d3d-11e7-9064-b51e23d463a4.png)

**Comment by reiterbene** [comment]
Letitas Design changes overally increased font sizes - this could fix the error: https://github.com/reiterbene/WikiDaheim/commit/5183f9ca1d1d5186ba76509985753bdac2cdd9e3
