### ISSUE TITLE
image not shown

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#170]
https://www.wikidaheim.at/Q699616 (Ebensee am Traunsee), Ebenseer Glöcklerlauf.

in https://de.wikipedia.org/wiki/Immaterielles_Kulturerbe_in_%C3%96sterreich#Q119732692 there is the Glöcklerlauf with an image, but the image is not shown in WikiDaheim App.

(mail already sent to Pixelhaufen)

**Comment by pixelhaufen** [comment]
'Bild', 'Video' and 'Audio' are not recognized by the frontend. Sending 'Bild' as 'Foto' seems to work as a fix.

**Comment by HerziPinki** [comment]
it's working now for Ebenseer Glöcklerlauf.

I do not have a test case at hand for Video & Audio. Is there still anything to do at the frontend?
