### ISSUE TITLE
missing entries from Denkmalliste

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#183]
See https://wikidaheim.at/Q665243 (Reichenau an der Rax)

the Huthaus (https://de.wikipedia.org/wiki/Liste_der_denkmalgesch%C3%BCtzten_Objekte_in_Reichenau_an_der_Rax#Q37956822) is not shown in the list, if filtering is done by just only Denkmale. 

There are 48 entries in https://de.wikipedia.org/wiki/Liste_der_denkmalgesch%C3%BCtzten_Objekte_in_Reichenau_an_der_Rax, but only 37 are shown when filtering by just Denkmale.
On the other hand, the Huthaus is shown by source WikiData and links to commonscat [Huthaus, Glockenhaus am Knappenberg, Reichenau an der Rax](https://commons.wikimedia.org/wiki/Category:Huthaus,_Glockenhaus_am_Knappenberg,_Reichenau_an_der_Rax).

Same for Pfarrkirche Edlach an der Rax, only shown via Wikidata linking to WP:de article in this case.

on the other hand 
Kath. Pfarrkirche hl. Barbara is shown with two data sources (Denkmalliste, Wikidata (linking to WP:de article)) - Filtering is done correctly, the object is shown only once when filtering for 'Weiteres', for 'Denkmale' or for both.

What is the difference?
Between Huthaus and Pfarrkirche Edlach an der Rax (and not causing the different behaviour, as both behave the same):

- Huthaus has no article, Pfarrkirche Edlach an der Rax  has one

What is the difference?
Between Huthaus and Pfarrkirche hl. Barbara (which might be the cause, as they show different behaviour)
?
their respective coords are identical in Denkmalliste & Wikidata

What is the difference?
Between Pfarrkirche Edlach an der Rax  and Pfarrkirche hl. Barbara (which might be the cause, as they show different behaviour)
?
their respective coords are identical in Denkmalliste & Wikidata & their articles

any idea?

Don't know whether this is frontend or backend.

**Comment by pixelhaufen** [comment]
All should work now (parsing problem fixed) except [Q2243233](https://de.wikipedia.org/wiki/Liste_der_denkmalgesch%C3%BCtzten_Objekte_in_Reichenau_an_der_Rax#Q2243233). There is no 'ObjektID' which is used as unique ID for the database for Denkmalliste. Can this be fixed in wp or is there another ID that can be used for Denkmalliste? (has to be present in all lists.. maybe WD-Item?)

**Comment by HerziPinki** [comment]
Yes, objects added after 2020 (which is the case for [Q2243233](https://de.wikipedia.org/wiki/Liste_der_denkmalgesch%C3%BCtzten_Objekte_in_Reichenau_an_der_Rax#Q2243233)) do not have an ObjectID. the ObjektID was replaced by HERIS-ID and as an id in our lists, by the WD-Item. So you are right, the key in the Denkmalliste is the WD-Item. So please use WD-Item as a key for Denkmalliste.

(we changed the anchor for table rows from ObjektID to WD-Item some years ago (last year?))

- There should be a WD-Item property for each element in the Denkmalliste.
- Most objects do have ObjektID and HERIS-ID in their WD-Items.
- In rare cases there is a replacement 'WD-Item Ref' containing the id of an referenced Item (see e.g. https://de.wikipedia.org/wiki/Liste_der_denkmalgesch%C3%BCtzten_Objekte_in_Unterach_am_Attersee#Q37976214 and the last entry in https://de.wikipedia.org/wiki/Liste_der_denkmalgesch%C3%BCtzten_Objekte_in_Unterach_am_Attersee#Q37976214 - no anchor provided for Mondsee) - in general see https://de.wikipedia.org/wiki/Wikipedia:WikiProjekt_%C3%96sterreichische_Denkmallisten/Gemeinde%C3%BCbergreifende_Objekte. I think, you can use in these cases 'WD-Item Ref' as a replacement for 'WD-Item' / ignore those - it is not tragic, when these referenced objects are not shown. Of course the main object, here in Unterach, has to be handled like all others. Uploading files from these referencing items will give them the coordinates of the referencing item - which is good.
- old objects (not in Denkmalschutz since before 2020) did not get an HERIS-ID in WD (there is none after the migration of IDs by BDA), but they will have also WD-Items.
- new objects put to Denkmalschutz after 2020 will only have HERIS-ID.

**Comment by HerziPinki** [comment]
the Huthaus in Reichenau is ok now
