### ISSUE TITLE
Bilderwunsch fulfilled, but still shown in app

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#188]
In https://de.wikipedia.org/wiki/K%C3%B6flach the Bilderwunsch in the Infobox was fulfilled on 2024-06-07: https://de.wikipedia.org/w/index.php?title=K%C3%B6flach&diff=prev&oldid=245718000&diffmode=source, but it is still there in the app.

https://wikidaheim.at/Q550434

the same image was added to Wikidata and is shown in the app correctly. Coordinates (should not matter) are the same for WP article and Wikidata entry.

Is there an update lag? Or something else?

same for https://de.wikipedia.org/wiki/Schloss_Neu-Pfannberg

**Comment by pixelhaufen** [comment]
Should be fixed with  #189
