### ISSUE TITLE
Update auf website content after merging pull request is weird / does not work as expected

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#195]
I'm doing a pull request, I create it, then I merge the pull request, I do a Confirm Merge
-> Pull request successfully merged and closed
When entering Wikidaheim.at, I get the message: Neue WikiDaheim-Version verfügbar, Möchtest du die Seite neu laden, um die aktuellste Version zu verwenden?
-> ok
and than I get the old content.
doing <ctrl> <shft> R
I get the new content for the current page.

but reloading that page takes me back to the old content.

Is there something wrong with me or with the config?

**Comment by HerziPinki** [comment]
eventually this is caused by multiple instances of wikidaheim.at in multiple browser tabs?

**Comment by reiterbene** [comment]
as I moved the compiler to vite this shold be gone now, as we do not cache the app as offline app anymore
