### ISSUE TITLE
Wikidaheim.at does not help with navigating Vienna

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#209]
For the next (2025 round). 
Looking for municipality Wien fails (we all know that). But it still is a bit weird, that 'Wien' fails silent. 
There is a complaint and the proposal, to map Wien to just Innere Stadt, Wien. Maybe there is a better solution? Entering Wien will open a drill down menu with all the districts?

**Comment by reiterbene** [comment]
added a small fix to react to "wien" and change the suggestions to only vienna districts.
