### ISSUE TITLE
Search for Semmering doesn't work

### ISSUE THREAD

**Issue by pkopetzky** [Wikimedia-Austria/WikiDaheim#36]
Searching for "Semmering" doesn't return any results - neither on the landing page nor when you search for it on the map layout.

**Comment by pixelhaufen** [comment]
the api delivers data: https://wikidaheim.at/api/api.php?format=json&action=query&type=data&longitude=15.83&latitude=47.646944&categories=denkmalliste|hoehle|kellergasse|naturdenkmal|publicart|commons or https://wikidaheim.at/api/api.php?format=json&action=query&type=data&wikidata=Q659891&wiki=1&categories=denkmalliste|hoehle|kellergasse|naturdenkmal|publicart|commons and I don't see anything wrong with the JSON. Can anyone find out what circumvents the site from displaying the data? Happy to change the api output if that helps, however I can't see a problem with the data.

**Comment by pixelhaufen** [comment]
mapbox delivers wrong wikidata id Q19842286. This is overwritten in the api to Q659891 now, however this is not actually fixed since a fix hast to come from mapbox and not us.

**Comment by pkopetzky** [comment]
Thanks! Will contact Mapbox about this
