### ISSUE TITLE
Search for "Oberperfuss" returns the municipality Ranggen

### ISSUE THREAD

**Issue by pkopetzky** [Wikimedia-Austria/WikiDaheim#38]
Searching for Oberperfuss returns the items and information for Ranggen. 
Might be a similar issue as with Semmering?

**Comment by pixelhaufen** [comment]
not related to wrong wikidata id issue for Semmering. problem with different coordinates (mapbox/wp). adjusted latitude and longitude in db to better match mapbox query result. fixed
