### ISSUE TITLE
Deep-link to municipality

### ISSUE THREAD

**Issue by simon04** [Wikimedia-Austria/WikiDaheim#43]
Allow deep-linking to a specific municipality, such as
* http://wikidaheim.at/?wikidata=Q1735
* http://wikidaheim.at/?gkz=70101

**Comment by pkopetzky** [comment]
@pixelhaufen Is that easily doable?

**Comment by pixelhaufen** [comment]
sorry, this is a fronted-question - so no idea.

**Comment by reiterbene** [comment]
It's doable bot not so easily, as the app itself needs more data to load a municipality which is normally already distributed by the place clicked or the search suggestion (ID, Name, Lat/Long).
The best solution would be to re-write the search and order logic (which has not been touched by this update) and move the current municipality ID and Map Center from Redux to React Router.

**Comment by BraveheartWikimedia** [comment]
Use Wikidata ID as the deeplink identificator.

**Comment by reiterbene** [comment]
included in the current release
