### ISSUE TITLE
Obtain competition text from Wikipedia?

### ISSUE THREAD

**Issue by simon04** [Wikimedia-Austria/WikiDaheim#45]
Currently, changes from [Wikipedia:WikiDaheim#Fotowettbewerb](https://de.wikipedia.org/wiki/Wikipedia:WikiDaheim#Fotowettbewerb) are manually synced from time to time. Another approach would be to query the Wikipedia API for the up-to-date version of the text: https://de.wikipedia.org/w/index.php?title=Wikipedia:WikiDaheim&action=render

**Comment by pkopetzky** [comment]
That's a great idea! Would that also work for wikilinks?

**Comment by pkopetzky** [comment]
This issue will be solved with auto-deploy as well as moving the content to html files for easier changes directly on the server in case auto-deploy doesn't work.
