### ISSUE TITLE
Remove text "Gemeinde hier suchen" when clicking on search bar

### ISSUE THREAD

**Issue by pkopetzky** [Wikimedia-Austria/WikiDaheim#48]
When activating the search bar on the main page, the text "Gemeinde hier suchen" doesn't disappear until you start to type, which caused some confusion with some users. Would it be possible to remove that text as soon as you activate the search bar?

**Comment by simon04** [comment]
The text is shown using the standard [HTML placeholder attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-placeholder).

We can change that, yes, either using some JavaScript code, or using the new [::placeholder](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder) selector:

```css
input:focus::placeholder {
  color: rgba(0,0,0,0);
}
```

**Comment by pkopetzky** [comment]
Great! :-) Is there a difference in behaviour?

**Comment by simon04** [comment]
The second way is not yet widely supported.

**Comment by pkopetzky** [comment]
Ok, so using Javascript would be preferrable at this point? Sounds good to me :-)

**Comment by pkopetzky** [comment]
Because the current behaviour is standard on most websites, it would be counter-intuitive to change this aspect (because more users would be confused by the text disappearing). So in the interest of affordance, we'll not do this :-)
