### ISSUE TITLE
Feedback für die neue Oberfläche

### ISSUE THREAD

**Issue by pkopetzky** [Wikimedia-Austria/WikiDaheim#52]
- Es wäre schön, wenn die Österreichkarte auf der Einstiegsseite schneller laden würde (dauert etwa 1-2 Sekunden)
- Die Österreichkarte auf der Einstiegsseite ist oben und unten abgeschnitten, es sollte die ganze Karte angezeigt werden.
- die Navi auf der Einstiegsseite über die Österreichkarte auf die Gemeinde Eisenerz (oder Tragöß - St. Kathrein, beides Steiermark) führt dazu, dass keinerlei Menü angezeigt wird. Erst die Auswahl einer Gemeinde wie Thörl 2x rechts von Eisenerz zeigt das Menü an.
- die Navi auf der Einstiegsseite Eisenerz, dann Thörl und dann wieder Eisenerz (jeweils durch Klick in die Gemeinde), zeigt die Pins nach wie vor in der Gemeinde Thörl an, die Liste der Objekte ist die von Thörl, aber die Überschrift wechselt auf Eisenerz. Ein Klick auf Wildalpen hingegen wechselt auch die Inhalte der Objektliste.
- Bei Objekten ohne Bild braucht es im Pin beim mouseover keinen Leerplatz für das nicht vorhandene Bild.
- Kann man das Hervorheben der Gemeinde opaque gestalten, sodass die untenliegende topografische Karte noch durchscheint?
- ich würde es besser finden, wenn bei mouseover über die selektierte Gemeinde diese analog zu den Nachbargemeinden hervorgehoben wird und der Gemeindename angezeigt wird. Es ist nicht unmittelbar einsichtig, warum alle Rundumgemeinden angezeigt werden, die ausgewählte aber nicht. Hat aber vermutlich Konflikte mit den sonstigen mouseover-Effekten (beim Pin etwa) zur Folge und wurde deshalb nicht gemacht (ev. nur die Grenzen highlighten?)
- Beim Wechseln zur Gemeinde über die neue Navigation wird die Gemeinde nicht ganz angezeigt (die gesamte Gemeinde im Viewport anzuzeigen, wäre natürlicher).
- Die Dropdownliste bei der Auswahl einer Gemeinde liegt hinter der Liste an Objekten und ist damit teilweise verdeckt. Die müsste immer oben liegen.

**Comment by pkopetzky** [comment]
Originally from https://de.wikipedia.org/wiki/Wikipedia_Diskussion:WikiDaheim#Anmerkungen_zur_neuen_Oberfläche

**Comment by reiterbene** [comment]
die Navi auf der Einstiegsseite über die Österreichkarte auf die Gemeinde Eisenerz (oder Tragöß - St. Kathrein, beides Steiermark) führt dazu, dass keinerlei Menü angezeigt wird. Erst die Auswahl einer Gemeinde wie Thörl 2x rechts von Eisenerz zeigt das Menü an.

die Navi auf der Einstiegsseite Eisenerz, dann Thörl und dann wieder Eisenerz (jeweils durch Klick in die Gemeinde), zeigt die Pins nach wie vor in der Gemeinde Thörl an, die Liste der Objekte ist die von Thörl, aber die Überschrift wechselt auf Eisenerz. Ein Klick auf Wildalpen hingegen wechselt auch die Inhalte der Objektliste.

Beim Wechseln zur Gemeinde über die neue Navigation wird die Gemeinde nicht ganz angezeigt (die gesamte Gemeinde im Viewport anzuzeigen, wäre natürlicher).
**known bugs, wird durch das Umstellen auf Gemeindekennziffer behoben**

Die Dropdownliste bei der Auswahl einer Gemeinde liegt hinter der Liste an Objekten und ist damit teilweise verdeckt. Die müsste immer oben liegen.
**wird mit der neuen Sidebar gefixt**

Es wäre schön, wenn die Österreichkarte auf der Einstiegsseite schneller laden würde (dauert etwa 1-2 Sekunden)
**Die Ladezeit von Mapbox selbst kann ich leider nicht beeinflussen, werde den init jedoch so verschieben, dass er bereits vor dem category request passiert**

**Comment by pkopetzky** [comment]
- Einschränkung auf einen (leeren) Themenbereich entfernt die Liste der Objekte links (ist ja leer), ok, aber der Scrollbar bleibt verloren hängen. 

- Einschränkung auf einen (leeren) Themenbereich entfernt die Liste der Objekte links (ist ja leer), ok, aber die Gemeinden unterhalb der Liste lassen sich nicht selektieren (vermutlich liegt da noch ein unsichtbares div drüber) - für den Benutzer ist das nicht einsichtig, warum es rechts vom Scrollbar geht und links nicht. Gemeinden, die etwas über den Bereich der Liste ragen, lassen sich selektieren.
