### ISSUE TITLE
Idea: Use TranslateWiki for translation

### ISSUE THREAD

**Issue by JeanFred** [Wikimedia-Austria/WikiDaheim#54]
I noticed d80b0a and the other commits related to i18n. The format matches perfectly the TranslateWiki format (see eg https://github.com/wikimedia/labs-tools-heritage/commit/07439771ca8e4854c4fb65e1a1704c09c7230a93#diff-05e704b6ade3705e6f6b9c384c29ab8c)

How about using TranslateWiki.net for i18n? Would be happy to do the legwork on this. :)

**Comment by pkopetzky** [comment]
Adding Bene and myself to discuss this on Monday.

**Comment by pkopetzky** [comment]
@JeanFred Which kind of access would translatewiki need and how would we translate the html pages? Bene mentioned that he could transform those into markups.

**Comment by JeanFred** [comment]
@pkopetzky Documentation lives at https://translatewiki.net/wiki/Translating:New_project and https://translatewiki.net/wiki/Setup_of_a_new_project. Not sure how up to date it is − best thing would be to liaise with @siebrand.

Access: docs say push-access to @translatewiki

HTML pages: You mean pages that do not use messages from source/translations/locales ? Can you point which ones? Not too sure to be honest − best ask Siebrand about what the best practice is :)

**Comment by pkopetzky** [comment]
The translations/versions of the html pages are stored here right now: https://github.com/Wikimedia-Austria/WikiDaheim/tree/master/source/js/views

**Comment by reiterbene** [comment]
@JeanFred @BraveheartWikimedia is this still a thing or can we close the issue?
