### ISSUE TITLE
Changing municipality in Firefox

### ISSUE THREAD

**Issue by pkopetzky** [Wikimedia-Austria/WikiDaheim#57]
Original description in German: "Kann die einmal gewählte Gemeinde auf der Startseite von wiki daheim nicht wechseln. Wenn ich eine andere Gemeinde anklicke erscheint zwar der Name der Angeklickten in der Kopfzeile aber die Bildervorschläge und andere Hochlademöglichkeiten beziehen sich weiterhin auf die zuvor gewählte Gemeinde. Selbst neu laden hilft nicht."

**Comment by reiterbene** [comment]
Habs gerade mit Firefox getestet - bei mir tritt das Problem nicht auf.

> Um dem Problem genauer auf die Spur zu gehen bräuchte ich detailliertere
Infos wie  Browserversion, OS, Fehler aus der JS-Konsole, ...

Das nicht neu laden der Liste kommt vom ausgelagerten Webworker. Dieser
kann zB. auch über einen Adblocker gesperrt sein.

**Comment by pkopetzky** [comment]
Ich frag mal wegen Adblocker nach :-) Wärs es einfach, bei Verwendung von Adblocker darauf hinzuweisen, dass die Funktionalität eingeschränkt sein könnte?

**Comment by reiterbene** [comment]
Hey!

Wenns wirklich am Adblocker liegt, dann ja. Ansonsten würd ich die Meldung
nicht einbauen, da sie mehr Leute überfordern als helfen würd.

lg
bene



*Benedikt Reiter*Webdesign- und Entwicklung

Mobil: +43 699 19 46 55 68  <javascript:void(0);>
Web: http://benereiter.com  <http://benereiter.com/>
Adresse: Landstraße 71-75 / 2A, 4020 Linz

Es gelten die AGB <http://benereiter.com/agb>.
