### ISSUE TITLE
Raise level of display for pins

### ISSUE THREAD

**Issue by BraveheartWikimedia** [Wikimedia-Austria/WikiDaheim#59]
Users have requested that the level at which individual pins are visible should be raised, because you have to zoom a lot to finally see the pins in areas populated by several pins. Ideally the pins should be visible one zoom level above the current setting (or however this is measured in Mapbox). Is that easy to do/set?

P.S.: This is more of an issue on mobile than on desktop, if that helps clarify the issue.

**Comment by reiterbene** [comment]
It's easily possible to adjust the moment the clusters change to individual pins but it has to be testet how this affects the apps stability on some devices with lower hardware specs.

**Comment by reiterbene** [comment]
fixed by adding the option to disable clustering
