### ISSUE TITLE
UploadWizard URL fixes

### ISSUE THREAD

**Issue by JeanFred** [Wikimedia-Austria/WikiDaheim#68]
When browsing WikiDaheim and trying a random upload, I was sent to Commons with the following URL:
```
https://commons.wikimedia.org/wiki/special:uploadWizard?campaign=wlm-at&fields[]=124694&captionlang=de&description=Gasthaus+zur+steirischen+Grenze&categories=Halltal+Gasthaus+zur+steirischen+Grenze
```
This results in the _description_ being set, but the _caption_ having a language code:
![2019-06-27-191100_1366x768_scrot](https://user-images.githubusercontent.com/364381/60286258-a5fea900-990f-11e9-8c1f-8a22c2b45448.png)

Per https://commons.wikimedia.org/wiki/Commons:Upload_Wizard/Fields_prefilling, you need to:
* use `descriptionlang` to set the description language code 
* also use `caption` to set the caption to the same value than the description

**Comment by pkopetzky** [comment]
Thanks, @pixelhaufen  has corrected the links, should be visible now or tomorrow at the latest. :-)
