### ISSUE TITLE
Cellar streets without a picture are not displayed when filterting for cellar streets

### ISSUE THREAD

**Issue by pkopetzky** [Wikimedia-Austria/WikiDaheim#71]
See https://de.wikipedia.org/wiki/Wikipedia_Diskussion:WikiDaheim#Kellergassen:_es_werden_nur_die_bereits_bebilderten_Gassen_vorgeschlagen? 

There are 24 cellar streets in Ziersdorf (https://de.wikipedia.org/wiki/Liste_der_Kellergassen_in_Ziersdorf), but only 19 are displayed when you click on the cellar street icon. Only those with a picture are displayed afterwards.

**Comment by pkopetzky** [comment]
Hi Bene,

are you sure this has been fixed? The example with Ziersdorf still seems to be having the same problem.

**Comment by reiterbene** [comment]
<img width="525" alt="Screenshot 2019-07-02 at 16 52 24" src="https://user-images.githubusercontent.com/9134368/60522729-d5cff700-9ce9-11e9-986c-7ab712b28f00.png">

yes - try to reload and clear your browser cache - maybe the old version of the app is cached on your side.

**Comment by pkopetzky** [comment]
Ah, yes, of course :-)
Thanks!
