### ISSUE TITLE
The certificate for wikidaheim.at expired on 2020-01-20

### ISSUE THREAD

**Issue by simon04** [Wikimedia-Austria/WikiDaheim#82]
![2020-01-26_22-24](https://user-images.githubusercontent.com/782446/73142051-ab30fb80-408a-11ea-95f8-c120b1b99491.png)

**Comment by BraveheartWikimedia** [comment]
Solved by Pixelhaufen, although not quite sure what caused this in the first place.

**Comment by simon04** [comment]
Thank you! The certificates issued by Let's Encrypt expire after three months and have to be renewed regularly.
