### ISSUE TITLE
Check security alerts and update dependencies, performance

### ISSUE THREAD

**Issue by BraveheartWikimedia** [Wikimedia-Austria/WikiDaheim#85]
Check if the security alerts have any impact on the project and update the dependencies to the newer versions. Please also check if the updates have any positive or negative effects on the project.

One other aspect is to check the performance of the map and interface and see if the new updates or new developments by Mapbox offer some performance gains that would make WikiDaheim more accessible.

**Comment by reiterbene** [comment]
dependencies upgraded, build-stack moved to futureproof create-react-app
