### ISSUE TITLE
Escape issue with apostrophies

### ISSUE THREAD

**Issue by BraveheartWikimedia** [Wikimedia-Austria/WikiDaheim#87]
When certain special characters are used in the name of a pin, the escape functionality gets a bit over-excited. One example is described at https://de.wikipedia.org/wiki/Wikipedia_Diskussion:WikiDaheim/Archiv_2020#escape_problem

**Comment by simon04** [comment]
Hi @pixelhaufen and @BraveheartWikimedia,

a typical pitfall in PHP are the _magic quotes_, see [`set_magic_quotes_runtime`](https://www.php.net/manual/en/function.set-magic-quotes-runtime.php) for the documentation. Typically, one would want to disable this magic.

A single [`urlencode`](https://www.php.net/manual/en/function.urlencode) should be enough for the `caption=` and `description=`.

**Comment by pixelhaufen** [comment]
Since php7 this _feature_ has been removed so it's not the problem. Found the __Esche \\\\\\\'\\\\\\\'Fraxinus excelsior\\\\\\\'\\\\\\\'__ already saved in the wrong way into the database. So I guess I must be over escaping while reading the data. Sorry for the confusion...

**Comment by pixelhaufen** [comment]
Should work now. Tried it with an ugly bugfix.

**Comment by reiterbene** [comment]
works, closing
