### ISSUE TITLE
Allow users to disable the marker clustering

### ISSUE THREAD

**Issue by simon04** [Wikimedia-Austria/WikiDaheim#89]
I hate marker clustering on all maps. Instead of showing me the real distribution and making the individual markers accessible, one gets a rather useless numeric overview.

Despite having a huge monitor, this map conveys rather little useful information:
![2020-04-28-230611_3840x2160_scrot](https://user-images.githubusercontent.com/782446/80539734-531ad580-89a8-11ea-97b2-853378c45358.jpg)

**Comment by reiterbene** [comment]
added in current release
