### ISSUE TITLE
Zoom in doesn't work on initial request

### ISSUE THREAD

**Issue by BraveheartWikimedia** [Wikimedia-Austria/WikiDaheim#96]
German:
Wenn eine Gemeinde aufgerufen wird, zoomt die Karte nicht auf die Gemeinde, sondern bleibt in der Gesamtösterreichansicht. Das geht am besten wenn du die Einstellungen zurücksetzt (übers WikiDaheim-Logo) und dann z.B. https://wikidaheim.at/Q277965 aufrufst. Da wird dann Mödling ganz oben im Eck angezeigt, und reinzoomen geht schwer, weil man sonst eine andere Gemeinde anklickt. 
English:
Reseting the application and calling a municipality via https://wikidaheim.at/Q277965 makes the map stay on the zoomed out Austria view instead of zooming into the municipality. Also makes it tricky to zoom in, since clicking somewhere outside of the queried municipality sends you to the other municipality (and the municipalities are very small when zoomed out completely).

**Comment by BraveheartWikimedia** [comment]
Hi Bene,

tried this just now and after initialising the map the first request still doesnt zoom in :-/

**Comment by reiterbene** [comment]
Please force reload with CMD/Strg+Shift+R, you still have the old version locally cached
