### ISSUE TITLE
Vienna map stays clickable even when zooming/selecting into district

### ISSUE THREAD

**Issue by BraveheartWikimedia** [Wikimedia-Austria/WikiDaheim#97]
When selecting a district of Vienna via the searchbox, the map does zoom in, but stays clickable, making navigation of the map more difficult/confusing.

**Comment by reiterbene** [comment]
Comes hand in hand with #92 due to some missing information in the mapbox layers.

**Comment by BraveheartWikimedia** [comment]
Was this always the case? I can't remember having this issue last year for example when searching for a district of Vienna. At least it shouldn't be clickable?

**Comment by reiterbene** [comment]
Mapbox now offers an own API for Boundaries - maybe we should switch to that? This should give us some extra performance and less data flaws (hopefully): https://www.mapbox.com/boundaries/

**Comment by BraveheartWikimedia** [comment]
Absolutely, I think that would spell an end to our troubles and offer a really nicely drawn map. Looks like the municipality ID is used, except for Vienna. Could you please look into this and let us know how much more effort this would be on your part?

**Comment by BraveheartWikimedia** [comment]
Hi Bene,

have the new shapes been included yet? At least on lower zoom levels the same aberrations exist, and Vienna has the same issue as described above.

**Comment by reiterbene** [comment]
Please force reload with CMD/Strg+Shift+R, you still have the old version locally cached

**Comment by BraveheartWikimedia** [comment]
Ah, yes, that worked, thank you :-)
