### ISSUE TITLE
WebGL errors/warnings with Firefox

### ISSUE THREAD

**Issue by BraveheartWikimedia** [Wikimedia-Austria/WikiDaheim#99]
Firefox still seems to be putting out WebGL errors - in one case it looks like this (German). I couldn't reproduce some of the console messages in my tests, might also have to do with stricter security/privacy settings:

Unbekannte Pseudoklasse oder Pseudoelement '-webkit-full-screen'.  Regelsatz wegen ungültigem Selektor ignoriert. mapbox-gl.css:1:195
Fehler beim Verarbeiten des Wertes für 'touch-action'.  Deklaration ignoriert. mapbox-gl.css:1:1053
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:2152
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:2607
Unbekannte Pseudoklasse oder Pseudoelement 'focus-visible'.  Regelsatz wegen ungültigem Selektor ignoriert. mapbox-gl.css:1:3071
Unbekannte Pseudoklasse oder Pseudoelement 'focus-visible'.  Regelsatz wegen ungültigem Selektor ignoriert. mapbox-gl.css:1:3150
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:4197
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:4999
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:6820
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:7908
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:9295
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:9649
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:13378
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:16461
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:21283
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:24467
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:29159
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. mapbox-gl.css:1:29547
Fehler beim Verarbeiten des Wertes für '-webkit-text-size-adjust'.  Deklaration ignoriert. _normalize.scss:11:2
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-autofill'.  Regelsatz wegen ungültigem Selektor ignoriert. _normalize.scss:431:1
Unbekannte Pseudoklasse oder Pseudoelement '-ms-value'.  Regelsatz wegen ungültigem Selektor ignoriert. _normalize.scss:441:1
Fehler beim Verarbeiten des Wertes für 'font-feature-settings'.  Deklaration ignoriert. _app.scss:3:2
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. _filters.scss:168
Unbekannte Eigenschaft 'backdrop-filter'.  Deklaration ignoriert. _resultlist.scss:296:6
Fehler beim Verarbeiten des Wertes für 'align-items'.  Deklaration ignoriert. _resultlist.scss:297:6
Fehler beim Verarbeiten des Wertes für 'font-feature-settings'.  Deklaration ignoriert. _cityinfo.scss:229:4
Farbe erwartet, aber '1px' gefunden.  Fehler beim Verarbeiten des Wertes für 'border-bottom-color'.  Deklaration ignoriert. _settings.scss:16:4
Unbekannte Eigenschaft 'backdrop-filter'.  Deklaration ignoriert. _settings.scss:49
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. mapbox-gl.js:29:309454
Fehler beim Verarbeiten des Wertes für 'user-select'.  Deklaration ignoriert. www.wikidaheim.at
Fehler beim Verarbeiten des Wertes für 'user-select'.  Deklaration ignoriert. www.wikidaheim.at
false index.jsx:90:13
Einige Cookies verwenden das empfohlene "sameSite"-Attribut inkorrekt. 3
Content Security Policy: Die Bericht-URI (about:blank) sollte eine HTTP- oder HTTPS-URI sein.
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://www.wikidaheim.at/55362ea69aeb0c8e53f7.worker.js festgestellt ("worker-src"). Ein CSP-Bericht wird gesendet.
Content Security Policy: Die Bericht-URI (about:blank) sollte eine HTTP- oder HTTPS-URI sein.
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf blob:https://www.wikidaheim.at/82397eb2-3d91-41e2-bbe7-3f4eff293a06 festgestellt ("worker-src"). Ein CSP-Bericht wird gesendet.
Content Security Policy: Die Bericht-URI (about:blank) sollte eine HTTP- oder HTTPS-URI sein.
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf blob:https://www.wikidaheim.at/82397eb2-3d91-41e2-bbe7-3f4eff293a06 festgestellt ("worker-src"). Ein CSP-Bericht wird gesendet.
false index.jsx:90:13
Content Security Policy: Die Bericht-URI (about:blank) sollte eine HTTP- oder HTTPS-URI sein. serviceWorker.js:59:5
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://www.wikidaheim.at/service-worker.js festgestellt ("worker-src"). Ein CSP-Bericht wird gesendet. serviceWorker.js:59:5
false index.jsx:90:13
Error during service worker registration: TypeError: ServiceWorker script at https://www.wikidaheim.at/service-worker.js for scope https://www.wikidaheim.at/ threw an exception during script evaluation. serviceWorker.js:97:14
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. mapbox-gl.js:29:309454
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. mapbox-gl.js:29:309454
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. mapbox-gl.js:29:309454
Fehler beim Verarbeiten des Wertes für 'user-select'.  Deklaration ignoriert. www.wikidaheim.at
false index.jsx:90:13
false index.jsx:90:13
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 6 mapbox-gl.js:29:309454

**Comment by reiterbene** [comment]
These are all warnings that can be safely ignored

- CSS-Warnings because there are webkit-specifig styles present
- Service Worker is being blocked (only needed for faster loading)
- Deprecated-Warnings for used WebGL-Functions: can be safely ignored
